version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.0.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Cache.xcodeproj -scheme "Cache-iOS" -sdk iphonesimulator clean
      - run: xcodebuild -project Cache.xcodeproj -scheme "Cache-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro' -enableCodeCoverage YES test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
